# Generated by Django 3.0.8 on 2020-09-07 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20200907_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.IntegerField(default=0)),
                ('video', models.IntegerField(default=0)),
                ('time', models.DateTimeField(verbose_name='date published')),
                ('log_level', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=200)),
                ('detection_status', models.DateTimeField(verbose_name='date published')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_time', models.CharField(max_length=200)),
                ('error_kind', models.CharField(max_length=200)),
                ('error_info', models.CharField(max_length=200)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detection.Video')),
            ],
        ),
    ]
