# Generated by Django 3.0.8 on 2020-09-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_error_log_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='detection_status',
            field=models.FloatField(default=0.0),
        ),
    ]
