# Generated by Django 3.0.8 on 2020-09-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_auto_20200907_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='video_num',
            field=models.IntegerField(default=0),
        ),
    ]
