# Generated by Django 3.0.8 on 2020-09-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_task_video_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detection_item',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(default='', max_length=200),
        ),
    ]
